### Course HandsOn

In [4]:
import pandas as pd

In [5]:
titanic = pd.read_excel('titanic3.xls', index_col = 'name')
titanic

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
"Allison, Master. Hudson Trevor",1,1,male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Miss. Helen Loraine",1,0,female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
"Zabour, Miss. Thamine",3,0,female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
"Zakarian, Mr. Ortin",3,0,male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [6]:
titanic.sort_index(inplace = True)
titanic

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Abbing, Mr. Anthony",3,0,male,42.0,0,0,C.A. 5547,7.5500,NaN,S,NaN,NaN,NaN
"Abbott, Master. Eugene Joseph",3,0,male,13.0,0,2,C.A. 2673,20.2500,NaN,S,NaN,NaN,"East Providence, RI"
"Abbott, Mr. Rossmore Edward",3,0,male,16.0,1,1,C.A. 2673,20.2500,NaN,S,NaN,190.0,"East Providence, RI"
"Abbott, Mrs. Stanton (Rosa Hunt)",3,1,female,35.0,1,1,C.A. 2673,20.2500,NaN,S,A,NaN,"East Providence, RI"
"Abelseth, Miss. Karen Marie",3,1,female,16.0,0,0,348125,7.6500,NaN,S,16,NaN,"Norway Los Angeles, CA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",2,1,female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C,12,NaN,"Lucca, Italy / California"
"van Billiard, Master. James William",3,0,male,NaN,1,1,A/5. 851,14.5000,NaN,S,NaN,NaN,NaN
"van Billiard, Master. Walter John",3,0,male,11.5,1,1,A/5. 851,14.5000,NaN,S,NaN,1.0,NaN
"van Billiard, Mr. Austin Blyler",3,0,male,40.5,0,2,A/5. 851,14.5000,NaN,S,NaN,255.0,NaN
"van Melkebeke, Mr. Philemon",3,0,male,NaN,0,0,345777,9.5000,NaN,S,NaN,NaN,NaN

In [7]:
titanic.loc['Abbott, Mr. Rossmore Edward']

pclass                         3
survived                       0
sex                         male
age                         16.0
sibsp                          1
parch                          1
ticket                 C.A. 2673
fare                       20.25
cabin                        NaN
embarked                       S
boat                         NaN
body                       190.0
home.dest    East Providence, RI
Name: Abbott, Mr. Rossmore Edward, dtype: object

In [8]:
titanic.loc[['Abbott, Mr. Rossmore Edward','van Billiard, Master. James William']]

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Abbott, Mr. Rossmore Edward",3,0,male,16.0,1,1,C.A. 2673,20.25,NaN,S,NaN,190.0,"East Providence, RI"
"van Billiard, Master. James William",3,0,male,NaN,1,1,A/5. 851,14.50,NaN,S,NaN,NaN,NaN

In [9]:
titanic.loc['amal']

KeyError: 'amal'

Import pandas

In [1]:
import pandas as pd

Read the `titanic3.xls` file and set 'name' as the index

Drop the following columns: `['home.dest', 'embarked', 'sibsp', 'parch']`

Filter out all the passengers which did not survive.

Considering that the **body** column is only used for passengers who did not survive, drop that column, and then do the same thing for the **survived** column.

What is the max **fare** in **3rd class**?

Rename the index name of 'name' to 'Passenger'

**BONUS**

Create a new column that's called "Free Coffee", insert 1 if a passenger is either in 1st or 2nd class, otherwise insert 0

Use value_counts() to verify that 3rd class doesn't get any free coffee